"""empty message

Revision ID: 20d341dd2ded
Revises: 94984f2b9d0c
Create Date: 2020-01-19 11:10:31.407468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d341dd2ded'
down_revision = '94984f2b9d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###
