"""empty message

Revision ID: 3d06653fe5c9
Revises: d3f78162d0db
Create Date: 2020-01-19 20:43:14.238355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d06653fe5c9'
down_revision = 'd3f78162d0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
