"""empty message

Revision ID: 42599a799eff
Revises: d8b77f424e16
Create Date: 2020-01-19 13:25:07.555356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42599a799eff'
down_revision = 'd8b77f424e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
