"""empty message

Revision ID: 80738cea7233
Revises: 42599a799eff
Create Date: 2020-01-19 13:27:05.125805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80738cea7233'
down_revision = '42599a799eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
