"""empty message

Revision ID: 887ff4337268
Revises: 4daec8937100
Create Date: 2020-01-19 17:05:02.912542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ff4337268'
down_revision = '4daec8937100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
