"""empty message

Revision ID: e625ebb32cb1
Revises: 20d341dd2ded
Create Date: 2020-01-19 11:14:48.635825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e625ebb32cb1'
down_revision = '20d341dd2ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Show', 'artist_image_link')
    # ### end Alembic commands ###
